<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TOH.Common\TOH.Common.csproj" />
    <ProjectReference Include="..\TOH.Networking\TOH.Network.csproj" />
  </ItemGroup>

</Project>
