CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "DataProtectionKeys" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "FriendlyName" text NULL,
    "Xml" text NULL,
    CONSTRAINT "PK_DataProtectionKeys" PRIMARY KEY ("Id")
);

CREATE TABLE "Players" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Level" integer NOT NULL,
    "Username" text NOT NULL,
    CONSTRAINT "PK_Players" PRIMARY KEY ("Id"),
    CONSTRAINT "AK_Players_Username" UNIQUE ("Username")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200613050918_Initial', '3.1.3');