CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "DataProtectionKeys" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "FriendlyName" text NULL,
    "Xml" text NULL,
    CONSTRAINT "PK_DataProtectionKeys" PRIMARY KEY ("Id")
);

CREATE TABLE "Players" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Level" integer NOT NULL,
    "Username" text NOT NULL,
    CONSTRAINT "PK_Players" PRIMARY KEY ("Id"),
    CONSTRAINT "AK_Players_Username" UNIQUE ("Username")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200613050918_Initial', '3.1.3');

CREATE TABLE "PlayerSessions" (
    "Id" text NOT NULL,
    "PlayerId" integer NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "ExpiresAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_PlayerSessions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PlayerSessions_Players_PlayerId" FOREIGN KEY ("PlayerId") REFERENCES "Players" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PlayerUnits" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "PlayerId" integer NOT NULL,
    "UnitId" integer NOT NULL,
    "Level" integer NOT NULL,
    CONSTRAINT "PK_PlayerUnits" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PlayerUnits_Players_PlayerId" FOREIGN KEY ("PlayerId") REFERENCES "Players" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_PlayerSessions_PlayerId" ON "PlayerSessions" ("PlayerId");

CREATE INDEX "IX_PlayerUnits_PlayerId" ON "PlayerUnits" ("PlayerId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200618055024_AddPlayerData', '3.1.3');
